Repository lenra-io/server, pull requests merged in 2023-10, with the labels that each got.

#471 feat: Manage functions requests and limits by env vars
  apps/lenra/lib/lenra/services/openfaas_services.ex
  config/config.exs
  config/runtime.exs
  docs/env-variables.md
  libs/application_runner/config/config.exs
  libs/application_runner/lib/services/application_services.ex
Labels: enhancement

#479 fix: OpenFaaS resources config
  .github/workflows/elixir_checks.yml
  apps/lenra/lib/lenra/services/openfaas_services.ex
  config/config.exs
  config/dev.exs
  config/prod.exs
  config/runtime.exs
  config/test.exs
  libs/application_runner/config/config.exs
  libs/application_runner/lib/services/application_services.ex
  mix.lock
Labels: bug

#476 feat!: Change CGU to CGS
  .vscode/thunder-tests/_db-backup/thunderCollection.json
  .vscode/thunder-tests/_db-backup/thunderclient.json
  .vscode/thunder-tests/collections/tc_col_lenra.json
  apps/identity_web/assets/css/cgs.css
  apps/identity_web/assets/js/app.js
  apps/identity_web/lib/identity_web/controllers/user_auth_controller.ex
  apps/identity_web/lib/identity_web/router.ex
  apps/identity_web/lib/identity_web/templates/user_auth/cgs-validation.html.heex
  apps/identity_web/priv/gettext/default.pot
  apps/identity_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/identity_web/priv/static/cgs/CGS_en_1.html
  apps/identity_web/priv/static/cgs/CGS_en_1.md
  apps/identity_web/priv/static/cgs/CGS_en_2.html
  apps/identity_web/priv/static/cgs/CGS_en_2.md
  apps/identity_web/priv/static/cgs/CGS_fr_1.html
  apps/identity_web/priv/static/cgs/CGS_fr_1.md
  apps/identity_web/priv/static/cgs/CGS_fr_2.html
  apps/identity_web/priv/static/cgs/CGS_fr_2.md
  apps/lenra/lib/lenra/accounts/user.ex
  apps/lenra/lib/lenra/errors/business_error.ex
  apps/lenra/lib/lenra/errors/technical_error.ex
  apps/lenra/lib/lenra/legal.ex
  apps/lenra/lib/lenra/legal/cgs.ex
  apps/lenra/lib/lenra/legal/user_accept_cgs_version.ex
  apps/lenra/lib/lenra/legal/user_accept_cgu_version.ex
  apps/lenra/lib/seeds.ex
  apps/lenra/lib/tasks/markdown_to_html.ex
  apps/lenra/priv/repo/migrations/20231002074351_cgu_to_cgs.exs
  apps/lenra/test/lenra/legal/cgs_test.exs
  apps/lenra/test/lenra/legal/cgu_test.exs
  apps/lenra/test/lenra/legal/user_accept_cgs_version_test.exs
  apps/lenra/test/lenra/legal/user_accept_cgu_version_test.exs
  apps/lenra/test/lenra/legal_test.exs
  apps/lenra/test/tasks/lenra_task_md2html_test.exs
  apps/lenra_web/lib/lenra_web/controllers/cgs_controller.ex
  apps/lenra_web/lib/lenra_web/controllers/cgu_controller.ex
  apps/lenra_web/lib/lenra_web/endpoint.ex
  apps/lenra_web/lib/lenra_web/plug/verify_cgs.ex
  apps/lenra_web/lib/lenra_web/router.ex
  apps/lenra_web/test/controllers/application_main_env_controller_test.exs
  apps/lenra_web/test/controllers/apps_controller_test.exs
  apps/lenra_web/test/controllers/build_controller_test.exs
  apps/lenra_web/test/controllers/cgs_controller_test.exs
  apps/lenra_web/test/controllers/cgu_controller_test.exs
  apps/lenra_web/test/controllers/deployment_controller_test.exs
  apps/lenra_web/test/controllers/environment_controller_test.exs
  apps/lenra_web/test/controllers/oauth2_controller_test.exs
  apps/lenra_web/test/controllers/runner_controller_test.exs
  apps/lenra_web/test/controllers/user_controller_test.exs
  apps/lenra_web/test/controllers/user_environment_access_controller_test.exs
  apps/lenra_web/test/controllers/webhooks_controller_test.exs
  apps/lenra_web/test/support/conn_case.ex
  docs/cgs-management.md
  docs/cgu-management.md
  libs/application_runner/lib/errors/business_error.ex
  libs/application_runner/test/controllers/resource_controller_test.exs
Labels: enhancement

#481 fix: @lenra system listeners like @lenra:navTo
  libs/application_runner/lib/event_handler.ex
Labels: bug

#485 fix: Error handling in OAuth
  apps/identity_web/lib/identity_web/controllers/user_auth_controller.ex
  apps/lenra_web/lib/lenra_web/controllers/user_controller.ex
  apps/lenra_web/lib/lenra_web/plug/verify_scope.ex
Labels: bug, help wanted
